version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ideaapp
      POSTGRES_PASSWORD: ideaapp
      POSTGRES_DB: ideaapp
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
